app/controllers/file_manager/mindmaps_controller.rb
app/models/mindmap.rb
app/views/file_manager/mindmaps/_list.html.slim
app/views/layouts/_head_items.html.slim

Icons Showing properly from directly opening from file manager eye icons

---

app/javascript/common/modals/make_private_modal.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treemaps/tree_map.vue

Confirm Password Field Added

---

app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss

Add Task on Button on top of Tasks in Kanban

---

app/controllers/mindmaps_controller.rb
app/javascript/common/modals/delete_modal.vue
app/javascript/common/modals/delete_password_modal.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treemaps/tree_map.vue
app/models/mindmap.rb
config/routes.rb

Mindmap Delete/Erase Functionality

---

app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss

Kanban - Reduce the number of clicks to edit/delete column Title

---

app/javascript/components/kanbans/kanban_new.vue
app/models/mindmap.rb

default the kanban stages so they have a starting point

---

app/controllers/stages_controller.rb
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss
app/models/stage.rb
db/migrate/20211126073758_add_position_to_stages.rb
db/schema.rb
package.json
yarn.lock

the kanban stages so they have a starting point

---

app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue

Fixed color Picker modal should remain open until user closes

---

app/javascript/components/treemaps/tree_map.vue

Should be able to export Tree Map

---

app/javascript/components/kanbans/kanban_new.vue

Should be able to export Kanban

---

app/javascript/components/treemaps/tree_map.vue

Added treemap support real time collaboration

---

app/javascript/components/treemaps/tree_map.vue

Tree Map - Update node Title should stick

---

app/javascript/components/home_page.vue

rename mConcept Maps to mSuite

---

app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue

Added more padding around child nodes

---

app/controllers/mindmaps_controller.rb
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treemaps/tree_map.vue
app/models/stage.rb

Kanban map - For each column, should include a "+" before each delete "x" icon; when clicked, add column to the right

---

app/javascript/common/navigation_bar.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/mindmaps/styles/mindmap_new.scss
app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue

menu bar should have the same options where applicable

---

app/controllers/stages_controller.rb
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss
app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue
db/migrate/20211206111021_add_bg_color_to_stage.rb
db/schema.rb

Kanban map - Should be able to change the background color of Stage Column using color picker

---

app/javascript/components/mindmaps/styles/idea_input_field.scss

Mindmap Nodes hide/show icons repositioned

---

app/javascript/components/treemaps/tree_map.vue
app/models/node.rb

Tree Map - able to drag N drop nodes

---

app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss
app/javascript/components/treemaps/tree_map.vue

 the color drop next to the + on treemap

---

app/javascript/components/home_page.vue
app/javascript/components/kanbans/kanban_new.vue

User can only open the previously saved map by entering unique key to second input field

---

app/controllers/mindmaps_controller.rb
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treemaps/tree_map.vue

Password protected maps deleted with wrong password

---

app/javascript/components/kanbans/kanban_new.vue

Kanban enhancement

---

app/javascript/components/kanbans/kanban_new.vue

Colorpicker not shown for unsaved stage

---

app/javascript/components/kanbans/kanban_new.vue

ColorPicker and Add not clickable for new stage until saved

---

app/javascript/components/home_page.vue

App Header name updated

---

app/javascript/common/navigation_bar.vue
app/javascript/common/styles/navigation_style.scss
app/javascript/components/home_page.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/whiteboard/whiteboard.scss
app/javascript/components/whiteboard/whiteboard.vue

Added title in the middle of navigation

---

app/javascript/components/treechart/tree_chart.vue

Worked on TreeChart Darg and drop nodes

---

app/controllers/mindmaps_controller.rb
app/javascript/components/home_page.vue
app/javascript/packs/home_page.js
app/models/mindmap.rb
config/routes.rb

MSuite name to use make a Unique_key

---

app/javascript/common/navigation_bar.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

Display 'Did you save the map key?' modal when logo clicked on TreeChart

---

app/javascript/components/home_page.vue

Fixed card wrap issues

---

app/javascript/components/whiteboard/whiteboard.scss
app/javascript/components/whiteboard/whiteboard.vue

Whiteboard Resize Functionality added

---

app/assets/stylesheets/mindmaps.scss
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

Font family changed to sans-serif

---

app/javascript/components/whiteboard/whiteboard.scss
app/javascript/components/whiteboard/whiteboard.vue

Fixed sidebar overflow of whiteboard

---

app/assets/stylesheets/mindmaps.scss
app/javascript/components/mindmaps/styles/mindmap_new.scss

Fixed Mindmap - Central Idea has font weight bold, which is inconsistent with the other maps.

---

app/controllers/mindmaps_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/common/styles/navigation_style.scss
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/whiteboard/whiteboard.vue
db/migrate/20220105120641_add_title_to_mindmap.rb
db/schema.rb

Title Added for all Apps

---

app/controllers/mindmaps_controller.rb
app/models/mindmap.rb

Fixed mSuite Validates

---

app/javascript/components/whiteboard/whiteboard.scss

Fixed whiteboard left sidebar overflow

---

Gemfile
app/controllers/mindmaps_controller.rb
app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/navigation_bar.vue
app/models/mindmap.rb
app/workers/file_in_active_worker.rb
config/application.rb
config/initializers/sidekiq.rb
config/schedule.yml
db/migrate/20220114171710_add_in_active_to_mindmap.rb
db/schema.rb

Worked on MSuite as a user I would like the option save the file as public, save the file as private or delete

---

app/javascript/components/dashboard.vue
app/javascript/components/home_page.vue
package.json

Worked on Cookies

---

app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue

Fixed display Confirm Delete Map modal for tree chart and tree map

---

app/javascript/common/modals/confirm_save_key_modal.vue

Worked on sometimes when X days is adjusted from 90 on Save Map Key modal, an Alert modal displays

---

app/javascript/common/modals/password_modal.vue

Added PASSWORD Modal 'Back to Home' button, so user has option to return to Home Screen

---

app/controllers/mindmaps_controller.rb
app/javascript/common/modals/make_private_modal.vue

Fixed simplify PASSWORD PROTECT modal when password already exists.

---

app/controllers/mindmaps_controller.rb
app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/navigation_bar.vue
app/javascript/components/home_page.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/export_to_word.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/mindmaps/modals/new_map_modal.vue
app/javascript/components/mindmaps_wrapper.vue
app/javascript/components/password_view.vue
app/javascript/components/shared/file_box.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue
app/javascript/routers/mindmaps.js
config/routes.rb

Worked on mSuite routes

---

app/javascript/components/whiteboard/whiteboard.vue

White board text font-family changed to sans-serif

---

app/javascript/components/whiteboard/whiteboard.vue

Worked on White Board map: When an element is selected, user should be able to adjust thickness by clicking increase/decrease.

---

app/javascript/components/kanbans/kanban_new.vue

Fixed action buttons on kanban

---

app/javascript/components/whiteboard/whiteboard.vue

Fixed Text button style on whiteboard

---

app/controllers/mindmaps_controller.rb
app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/components/treechart/tree_chart.vue

Worked on should be able to change the background color of Central Idea node in tree chart.

---

app/javascript/components/whiteboard/whiteboard.vue

Worked on white board element should stay selected, until user clicks off of it.

---

app/workers/file_in_active_worker.rb

Fixed sidekiq getting error when deletings.

---

app/javascript/components/whiteboard/whiteboard.vue

Worked on White Board Map: Should display Update Color modal when 'Color' button is clicked with an element selected.

---

app/javascript/components/whiteboard/whiteboard.vue

Worked on whiteboard element object increase or decrease its line thickness.

---

app/javascript/components/whiteboard/whiteboard.vue

Added white board hover style for all buttons.

---

app/javascript/components/whiteboard/whiteboard.vue

Worked on color modal should completely display when a Text object is selected.

---

app/views/layouts/_navbar.html.slim

Worked on unless menu items will be included on index header bar, remove hamburger link.

---

app/javascript/components/mindmaps/mindmap_new.vue

Worked on clicking 'Save Private' should display the PASSWORD modal on Mindmap, just like the other map types.

---

.github/workflows/rubocop-analysis.yml
app/javascript/common/modals/confirm_save_key_modal.vue

Added all apps in the suite save button.

---

app/workers/file_in_active_worker.rb

Worked on file inactive worker

---

app/javascript/common/navigation_bar.vue

Fixed mindmaps header and treechart headers are misaligned.

---

app/assets/stylesheets/common.scss
app/javascript/common/navigation_bar.vue

Added 'Save' button on header bar display text on hovered.

---

app/assets/stylesheets/common.scss
app/javascript/components/kanbans/styles/kanban_new.scss

Fixed kanban background color issues.

---

app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/modals/make_private_modal.vue
app/javascript/common/navigation_bar.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

Worked on Clicking Logo, then Save Private with Password, should return to Index screen after success message displays.

---

app/javascript/components/mindmaps/mindmap_new.vue

Removed 'Save Private' button in mindmap.

---

app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue

Fixed redirect issue after verify password model

---

app/javascript/common/modals/make_private_modal.vue

Password Protect modal: Change text 'Old' to lowercase, to be consistent

---

app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue

Fixed for Tree Chart or Tree Map 'Save Private' button redirect issue

---

app/javascript/components/whiteboard/whiteboard.vue

Worked on newly included object the only selected object on the White Board.

---

app/javascript/components/treechart/tree_chart.vue

Added tooltip  'Add Child Node' in TreeChart.

---

app/javascript/components/treemaps/tree_map.vue

Changed color plus icon in TreeMap

---

app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue

Worked on TreeChart and TreeMap added ToolTip.

---

app/javascript/components/whiteboard/whiteboard.vue

Fixed reset issues on select element in WhiteBoard

---

app/javascript/components/treechart/tree_chart.vue

Fixed TreeChart Color Picker and Add Child icons issues

---

app/javascript/components/treechart/tree_chart.vue

Cap 'C' for 'child' in TreeChart

---

app/javascript/components/whiteboard/whiteboard.vue

Fixed bug of select and deselect element in white board.

---

app/javascript/components/whiteboard/whiteboard.vue

Fixed reset issue whiteboard

---

app/javascript/components/mindmaps/mindmap_new.vue

Fixed simple mindmap reset issue.

---

app/javascript/components/whiteboard/whiteboard.vue

Worked on White board,After creating new element,New element should stay selected. 

---

app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/home_page.vue
app/javascript/components/mindmaps_wrapper.vue
app/models/mindmap.rb
package.json

Added Flow map as type of map.

---

app/javascript/components/whiteboard/whiteboard.vue

Bug:: fixed white board color picker cancel button issue.

---

app/javascript/components/flowmap/flowmap.vue

Changed arrows in flow map

---

app/javascript/common/navigation_bar.vue

Worked on Flow Map: Should remove Delete button from top menu

---

app/javascript/components/recaptcha.vue

Worked on captcha be positioned in the middle of the screen.

---

db/migrate/20220405072629_change_data_type_of_mindmap_canvas.rb
db/migrate/20220406113251_add_canvas_to_mindmap.rb

Worked on canvas migration issue.

---

app/javascript/components/flowmap/flowmap.vue

Fixed issues in Flow Map

---

db/migrate/20220406113251_add_canvas_to_mindmap.rb
db/migrate/20220408053504_add_canvas_to_mindmap_and_alter_table.rb
db/schema.rb

Fixed duplicate column name 'canvas' issue.

---

app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
package.json

Worked on replace existing Flow Map with copy of Tree Chart, but make it function horizontally.

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/treechart/tree_chart.vue

Bug fixes entering data duplicates TreeChart and TreeMap.

---

app/javascript/components/dashboard.vue
app/javascript/components/home_page.vue

Worked on if there are no values configured for captcha, then captcha should be disabled.

---

app/controllers/stages_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue
config/routes.rb

Reset button added for all maps in navbar.

---

app/javascript/components/mindmaps/mindmap_new.vue

Fixed Mindmap: Fix line drawing and hand location when user creates a node.

---

app/javascript/components/mindmaps/mindmap_new.vue

Fixed line drawing and hand location when user creates a node in sample mindmap.

---

app/controllers/mindmaps_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue
app/javascript/store/TreeMap.js
app/models/mindmap.rb

Fixed all maps should reset to default when user Confirms Reset

---

app/controllers/home_controller.rb
app/controllers/mindmaps_controller.rb
app/views/home/page_404.html
config/routes.rb

Worked on update the message that displays when the map gets deleted.

---

app/controllers/concerns/node_concern.rb
app/controllers/nodes_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/components/home_page.vue
app/javascript/components/mindmaps_wrapper.vue
app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/datepicker.css
app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css
app/models/mindmap.rb
app/models/node.rb
db/migrate/20220414093510_add_due_date_in_todos.rb
db/schema.rb
package.json

Added ToDo as type of Map.

---

app/javascript/components/flowmap/flowmap.vue

Fixed design flow map.

---

app/javascript/common/navigation_bar.vue
app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Fixed Todo app issue sweet modal and data picker.

---

app/javascript/components/home_page.vue

Fixed captcha issue.

---

app/javascript/components/todo/todo_style.css

Fixed Scroll Bar in Todo

---

app/javascript/components/todo/TodoMap.vue

Fixed remove duedate from todo

---

app/controllers/nodes_controller.rb

Add child status update solved

---

app/controllers/concerns/node_concern.rb

Todo: Fixed parent status incomplete child should not affected

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

Todo: Child Filter Fixed

---

app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Todo: Fixed Title Should not be blank or empty space

---

app/javascript/components/todo/todo.vue

Todo: Fixed Date issue

---

app/javascript/components/todo/todo.vue

Todo: changed cancel icon

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Todo: Added reset button in Parent Todo and added tooltip

---

app/javascript/components/todo/todo.vue

Todo: changed save icon

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

Todo: Fixed child due date issue.

---

app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Todo: Fixed design overflow issue.

---

app/javascript/components/todo/todo.vue

Todo: Fixed Title Update Issue

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

Todo: Changed save icon.

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Todo: Fixed UI issue.

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

Todo: Fixed align icons and date

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

Todo: Fixed update date issue

---

app/javascript/components/todo/todo.vue

Todo: Fixed reset issue.

---

app/javascript/components/home_page.vue

Fixed design of landing page

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Fixed todo issues.

---

app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Todo: Fixed toggle button design.

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo_style.css

Todo: Fixed checked todo line through color.

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/home_page.vue
app/javascript/components/todo/todo_style.css
app/javascript/components/treechart/style/tree_chart.scss

Fixed scrollbar on map.

---

app/javascript/components/home_page.vue

Fixed dashboard designed

---

app/javascript/common/navigation_bar.vue
app/javascript/components/notepad/notepad.vue

Notepad: Added auto save functionality

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo_style.css

Todo: Added 'X' on Date Picker on hover.

---

app/javascript/common/navigation_bar.vue

Added Delete button in all maps.

---

app/controllers/api/settings_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/components/beta.vue
app/javascript/components/dashboard.vue
app/javascript/components/home_page.vue
app/javascript/components/mindmaps/styles/mindmap_new.scss
app/views/home/index.html.slim
app/views/mindmaps/index.html.slim
db/migrate/20220603071933_add_beta_status_to_setting.rb
db/schema.rb
vendor/assets/javascripts/active_admin.js

Added Beta Disclaimer.

---

app/javascript/components/treemaps/tree_map.vue

Fixed editing a node should have the same box with white background as adding a node.

---

app/controllers/api/settings_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/components/beta.vue
app/views/home/index.html.slim
app/views/mindmaps/index.html.slim
db/migrate/20220606143053_add_beta_url_to_settings.rb
db/schema.rb
vendor/assets/javascripts/active_admin.js

Added Beta HyperLink

---

app/views/layouts/_navbar.html.slim

fixed anchor links on navbar

---

app/javascript/components/notepad/notepad.vue

Fixed Notepad Design.

---

app/javascript/common/modals/comment_map_modal.vue

Fixed issue mindmap attachment has bizzare purple circles

---

app/javascript/components/mindmaps/modals/attachment_modal.vue
app/javascript/components/mindmaps/modals/central_attachment_modal.vue

Fixed there should be no 'edit' button for mindmap comments. just start editing.

---

app/javascript/components/notepad/notepad.vue

Notepad Removed attachment feature

---

app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue

Fixed Real Time Collaboration

---

app/javascript/components/kanbans/styles/kanban_new.scss

Fixed Default Stage background is light grey, not white.

---

app/javascript/components/mindmaps/mindmap_new.vue

Fixed mindmap mouse pos

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

Fixed ToDo map: Should not be able to Save Parent with Date earlier than any of its unchecked Children.

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/styles/kanban_new.scss
app/javascript/components/treechart/style/tree_chart.scss
app/javascript/components/treechart/tree_chart.vue

Fixed scrollbrs on kanban,treechart and flowmap.

---

app/javascript/common/modals/comment_map_modal.vue

Comments: Fixed issue and added functionality edit remove in reply. 

---

app/javascript/components/whiteboard/whiteboard.vue

Fixed WhiteBoard: The color of the Line drawn should be the last color used, instead of always black by default.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Changed line icon

---

app/javascript/components/mindmaps/modals/attachment_modal.vue
app/javascript/components/mindmaps/modals/central_attachment_modal.vue

Fixed mindmap edit box closes on click enter key.

---

app/javascript/components/treechart/style/tree_chart.scss

Fixed flowMap alignment.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Added Selection Tool.

---

app/javascript/common/modals/comment_map_modal.vue
app/javascript/common/navigation_bar.vue

Fixed comments indicator.

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/packs/map_dashboard.js

Added recent colors in color picker.

---

app/javascript/components/whiteboard/whiteboard.vue

Fixed WhiteBoard issue.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Fixed Selection Issue on TEXT.

---

app/models/mindmap.rb

Fixed TreeMap, TreeChart, and FlowMap: Clicking 'Reset' changed the background color of Central Idea to default color.

---

app/javascript/components/mindmaps/modals/attachment_modal.vue
app/javascript/components/mindmaps/modals/central_attachment_modal.vue

Mindmap: Disabled file upload option.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Fixed Straight Line issue.

---

app/assets/stylesheets/common.scss

Fixed home page scroll bar.

---

app/javascript/components/notepad/notepad.vue

Notepad: Fixed Real time collaboration

---

app/assets/stylesheets/common.scss
app/javascript/components/home_page.vue

Fixed scroll bar issue on homepage

---

app/javascript/common/navigation_bar.vue
app/javascript/components/home_page.vue
app/javascript/components/mindmaps_wrapper.vue
app/javascript/components/spreadsheet/spreadsheet.vue
app/models/mindmap.rb
package.json

Added Spread sheet.

---

app/javascript/components/spreadsheet/spreadsheet.vue

Fixed spreadsheet responding to screen-sizes greater than 1080p resulting in blank space to the right and the bottom

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/mixins/common.js

Fixed: Font Color Responsiveness

---

app/javascript/components/mindmaps/mindmap_new.vue

Fixed Mindmap: User should be able to include Description after Central node is active.

---

app/javascript/components/mindmaps/idea_input_field.vue
app/javascript/components/mindmaps/mindmap_new.vue

Removed paperclip icon and worked on comment icon.

---

app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/mindmaps/modals/attachment_modal.vue
app/javascript/components/mindmaps/modals/central_attachment_modal.vue

Mindmap: Fixed Description Box Issue.

---

app/javascript/common/navigation_bar.vue
app/javascript/components/spreadsheet/spreadsheet.vue
app/javascript/components/spreadsheet/styles/bossanova.css
app/javascript/components/spreadsheet/styles/jsuites.css
package.json

SpreadSheet: Fixed

---

app/javascript/components/spreadsheet/spreadsheet.vue
app/javascript/components/spreadsheet/styles/bossanova.css
app/javascript/components/spreadsheet/styles/jsuites.css

Fixed horizontal scrollbar in spreadsheet.

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/mixins/common.js

Fixed responsive color issue.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Improved Drawing Experience

---

app/javascript/components/spreadsheet/spreadsheet.vue
app/models/mindmap.rb

Fixed Spreadsheet reset issue.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Fixed requierd workflow

---

app/javascript/components/spreadsheet/spreadsheet.vue

SpreedSheet fixed reset columns issue.

---

app/javascript/components/mindmaps/mindmap_new.vue

Mindmap Fixed update central node name

---

app/javascript/components/notepad/notepad.vue

Notepad: Fixed text bold issue.

---

app/models/node.rb

Fixed FlowMap: Drag 'N Drop should not change the background color of nodes.

---

app/javascript/components/mindmaps/mindmap_new.vue

Mindmap Fixed central map field.

---

app/javascript/components/mindmaps/mindmap_new.vue

Mindmap: Fixed child note update field issue.

---

app/javascript/components/whiteboard/whiteboard.vue

Fixed color model issue when not selected element.

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/treechart/tree_chart.vue

TreeChart and FlowMap: Fixed Clicking Delete node should delete that node and its descendants.

---

app/javascript/components/spreadsheet/spreadsheet.vue

Spreadsheet: Fixed Clicking 'Reset' should have removed sort icon from column header.

---

app/javascript/components/whiteboard/whiteboard.vue

Fixed whiteboard element selected issue.

---

app/javascript/common/navigation_bar.vue

Added Due Date tooltip in Save button

---

app/javascript/common/navigation_bar.vue

Fixed show will delete at date in tooltip.

---

app/javascript/components/notepad/notepad.vue

Fixed notepad: from time to time the cursor will go back to the beginning of the document and keep going back.

---

app/javascript/components/flowmap/flowmap.vue

FlowMap: Fixed overflow.

---

app/controllers/nodes_controller.rb
app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/models/node.rb

Todo: Added drag and drop functionality.

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/treechart/tree_chart.vue

Fixed TreeChart and FlowMap: Should be able to just delete untitled node.

---

app/javascript/components/spreadsheet/spreadsheet.vue

Fixed reset whiteboard arrow up or down issue.

---

app/controllers/mindmaps_controller.rb
app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/mindmaps_wrapper.vue
app/javascript/components/notepad/notepad.vue
app/javascript/components/spreadsheet/spreadsheet.vue
app/javascript/components/todo/todo.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

Fixed Exp days issue.

---

app/javascript/components/spreadsheet/styles/bossanova.css

Spreadsheet map: added margin between select icon.

---

app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/treemaps/tree_map.vue

Fixed Create Node issue

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Fixed Straight Line Selection

---

app/javascript/common/modals/color_palette_modal.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss
app/javascript/components/treechart/style/tree_chart.scss
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue
package.json

Feature: Added Color Pallete.

---

app/javascript/common/navigation_bar.vue
app/javascript/components/spreadsheet/spreadsheet.vue

SpreadSheet: Fixed Export Issue and closed modal.

---

app/javascript/components/spreadsheet/spreadsheet.vue

SpreadSheet: Fixed real Time Collaboration and Reset Function.

---

app/javascript/components/spreadsheet/spreadsheet.vue

SpreadSheet: Fixed Download Issue

---

app/javascript/components/flowmap/flowmap.vue
app/javascript/components/treechart/tree_chart.vue
app/models/node.rb

TreeChart FlowMap: Fixed New Title Issue

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Feature Added to change the layer of an object forward or backward

---

app/javascript/components/spreadsheet/spreadsheet.vue

Spredsheet: Changed sorting icons.

---

app/channels/web_notifications_channel.rb
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/notepad/notepad.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/models/node.rb

Fixed Names of Nodes

---

app/javascript/common/modals/color_palette_modal.vue
app/javascript/components/treemaps/tree_map.scss

TreeMap: Added more space between nodes and modal issue.

---

app/javascript/components/spreadsheet/spreadsheet.vue

Spreadsheet: Fixed Editing label issue

---

app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue

TreeMap: Fixed issues.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Fixed unselect object on cancel button click.

---

app/javascript/components/kanbans/kanban_new.vue

Kanban: Fixed Title Issue.

---

app/javascript/components/kanbans/kanban_new.vue

Kanban: Fixed title issue

---

app/javascript/common/navigation_bar.vue
app/javascript/components/whiteboard/whiteboard.vue

Whiteboard: Fixed issue.

---

app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue

Fixed TreeMap: Node buttons overlap Title

---

app/javascript/components/treemaps/tree_map.scss

TreeMap: Added more margin top in label.

---

app/javascript/mixins/common.js

Tree_Chart: Fixed Color issue on buttons

---

app/controllers/mindmaps_controller.rb
app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/navigation_bar.vue
app/javascript/components/mindmaps_wrapper.vue
app/javascript/components/notepad/notepad.vue
app/javascript/components/spreadsheet/spreadsheet.vue
config/routes.rb

Worked on mSuite immediately deleted when nothing was done on it.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Fixed Colors Issue

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Fixed element should remain selected

---

app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue

TreeMap: Fixed Overlap title.

---

app/javascript/components/notepad/notepad.vue

Notepad: Cursor Fixed

---

app/javascript/components/whiteboard/whiteboard.vue

Whiteboard: Fixed Object displayed selected as if invisible.

---

app/javascript/components/whiteboard/whiteboard.vue

WhiteBoard: Fixed reset color issue and object displayed selected as invisible.

---

app/javascript/common/modals/confirm_save_key_modal.vue

Fixed mSuite update will delete date issue.

---

app/javascript/components/whiteboard/whiteboard.vue
app/javascript/mixins/common.js

WhiteBoard: Fixed stroke text and also selected color issue.

---

app/controllers/mindmaps_controller.rb

Fixed Sometimes when reload was clicked while collaborating on a map, the shared screen returned to index

---

app/javascript/common/modals/user_map_modal.vue
app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/idea_input_field.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/mindmaps/modals/central_attachment_modal.vue
app/javascript/components/notepad/notepad.vue
app/javascript/components/spreadsheet/spreadsheet.vue
app/javascript/components/todo/todo.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

Enhancement Temporary User: Added

---

app/assets/stylesheets/common.scss
app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/navigation_bar.vue

Worked on Update top menu buttons and move position of Editing/Edited text below.

---

app/assets/stylesheets/common.scss
app/javascript/common/navigation_bar.vue

Update navbar designed

---

app/javascript/common/modals/user_map_modal.vue

User modal: Fixed user name

---

app/javascript/common/modals/user_map_modal.vue
app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/notepad/notepad.vue
app/javascript/components/spreadsheet/spreadsheet.vue
app/javascript/components/todo/todo.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

Temp User: code refactored

---

lib/document.rb

Fix for 500 errors for Missing id field

fix for 500 error missing 'id'

---

app/javascript/components/whiteboard/whiteboard.vue

Whiteboard: Fixed  issues.

---

lib/document.rb

Fix for 'TypeError (no implicit conversion of nil into String):'

Fix for 'TypeError (no implicit conversion of nil into String):'

---

app/javascript/components/treemaps/tree_map.vue

Fixed Tree Map node Title clicked off still remains white.

---

app/javascript/components/spreadsheet/spreadsheet.vue

Fixed Spreadsheet: Sometimes when map creator shares URL before editing map first, maps might get stuck and don't consistently update.

---

app/javascript/components/treemaps/tree_map.vue

Fixed TreeMap background should be transparent

---

app/controllers/nodes_controller.rb
app/controllers/stages_controller.rb
app/javascript/components/kanbans/kanban_new.vue

Fixed Kanban map: Background colors for Stages should update according to selected color scheme and also reset issue.

---

app/controllers/nodes_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/components/mindmaps/mindmap_new.vue

Fixed Navbar issue

---

app/javascript/components/spreadsheet/spreadsheet.vue

Spreadsheet: row fixed

---

app/controllers/stages_controller.rb
app/javascript/components/kanbans/kanban_new.vue

Fixed kanban reset issue.

---

app/javascript/components/mindmaps/idea_input_field.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

 Enhancment Added: Touchscreen in mindmap and whiteboard

---

app/javascript/common/navigation_bar.vue
app/javascript/components/whiteboard/whiteboard.vue

Whiteboard: Fixed reset issue

---

app/javascript/components/mindmaps/mindmap_new.vue
db/schema.rb

Fixed mindmap central idea update issue and also update schema file

---

app/javascript/common/modals/add_calendar_event_modal.vue

Calendar: Removed event type and update label event form.

---

app/javascript/common/modals/add_calendar_event_modal.vue

Calendar: Event time formate update

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/common/modals/recurring_calendar_event_modal.vue
app/javascript/components/calendar/calendar.vue
app/javascript/mixins/common.js

Bug Fixed: Calendar: Sometimes, unable to Add Recurrence when On date selected, since Continue button remains disabled.

---

app/javascript/common/modals/recurring_calendar_event_modal.vue

Fixed: Calendar: Update event with Add Recurrence On date selected, last day of week selected should be included on Calendar

---

app/javascript/components/calendar/calendar.vue

Fixed: Calendar: should include Editing by: and Last Edited by below header bar buttons.

---

app/javascript/components/mindmaps/mindmap_new.vue

Mindmap: Fixed central idea update issue.

---

app/javascript/components/mindmaps/mindmap_new.vue

Mindmap: Fixed node drag and create sbling issue.

---

config/initializers/sidekiq.rb

Redis: Fixed url issue in sidekiq

---

app/javascript/common/navigation_bar.vue
app/javascript/components/calendar/calendar.vue

Resolved: Calendar: Exported file missing Month/Year for all views.

---

app/javascript/components/calendar/calendar.vue

Resolved Calendar should automatically update without reload browser (create, edit, delete).

---

app/javascript/components/calendar/calendar.scss
app/javascript/components/calendar/calendar.vue

Resolved: Calendar - Month view: Should display more than one entry at a time on Events Listing modal that displays when # more link is clicked.

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/components/calendar/calendar.vue

Fixed: Calendar: Should always have option to include Time with Date on Event Forms.

---

config/initializers/sidekiq.rb

Sidekiq: Fixed for client side redis url.

---

app/javascript/components/poll/polls/create_poll.vue

TreeChart & FlowMap: Design Fixed

---

app/controllers/mindmaps_controller.rb
app/javascript/components/poll/poll.vue
app/javascript/components/poll/polls/create_poll.vue
app/javascript/components/poll/polls/poll.css
app/javascript/components/poll/polls/poll_view.vue
app/javascript/components/poll/polls/poll_view_results/poll_results.vue
app/javascript/components/poll/polls/voting_poll.vue

#883 
#885 
#885 
#887 
#888 
#890 
#892 
#893

Poll: Fixed issues

---

app/javascript/common/modals/add_calendar_event_modal.vue

Worked on calender event form.

---

app/controllers/concerns/history_concern.rb
app/controllers/nodes_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/components/calendar/calendar.vue

Worked on Calendar  Undo and Redo buttons on header bar.

---

app/javascript/components/mindmaps_wrapper.vue
app/javascript/components/spreadsheet/spreadsheet.vue

#788 
#819 
#873 
#875 
#834 
#874

Spreadsheet: Fixed issues.

---

app/javascript/components/calendar/calendar.vue

Fixed: Calendar: Should remain displayed in Week or Day view when selected, even when events do not exist.

---

app/models/mindmap.rb

Spreadsheet: reset fixed

---

app/javascript/common/modals/add_calendar_event_modal.vue

Worked on calendar description not be required.

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/components/notepad/notepad.vue

Worked on Notepad: Clicking 'B' active should change selected text to Bold.

---

app/javascript/components/calendar/calendar.scss

Added: calendar view display 2 lines.

---

app/javascript/components/calendar/calendar.vue

Worked on Calendar - Add Event Form: Change default End Time.

---

app/javascript/components/notepad/notepad.vue

Fixed: Notepad map Alignment button should be active dependent upon selected text.

---

app/javascript/components/notepad/notepad.vue

Fixed notepad issue.

---

app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

Added All maps: Edit Text should not display until an actual change was made to the map.

---

app/javascript/common/navigation_bar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue

Worked on Added : All maps: Edit Text should not display until an actual change was made to the map.

---

app/javascript/components/poll/polls/poll_view.vue
app/javascript/components/poll/polls/poll_view_results/poll_results.vue

Poll: Fixed voters

---

app/javascript/components/poll/polls/voting_poll.vue

Poll: Export Fixed

---

app/javascript/components/poll/poll.vue
app/javascript/components/poll/polls/poll_view.vue

Poll: Edit Button Fixed

---

app/javascript/components/calendar/calendar.vue
app/javascript/components/flowmap/flowmap.vue
app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/notepad/notepad.vue
app/javascript/components/spreadsheet/spreadsheet.vue
app/javascript/components/todo/todo.vue
app/javascript/components/treechart/tree_chart.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/components/whiteboard/whiteboard.vue
app/javascript/mixins/temporary_user.js

Temporary user: On load user should display, fixed.

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Todo: Fixed issues

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/common/modals/color_palette_modal.vue
app/javascript/components/calendar/calendar.scss
app/javascript/components/calendar/calendar.vue
app/javascript/components/treemaps/tree_map.vue

Worked on calendar event color.

---

app/javascript/components/kanbans/kanban_new.vue
app/javascript/components/kanbans/styles/kanban_new.scss

Worked on kanban issues

---

app/javascript/components/notepad/notepad.vue

Worked on size small for numbered list.

---

package.json
yarn.lock

resolves sec alert for url-parse

Sec alerts928

---

app/javascript/components/notepad/notepad.vue

Worked on notepad rest issue.

---

app/javascript/components/whiteboard/whiteboard.vue

Worked on whiteboard rest issue.

---

app/javascript/components/mindmaps/mindmap_new.vue

Mindmap: glitch fixed

---

app/javascript/components/poll/polls/create_poll.vue
app/models/mindmap.rb

Poll: Url copy fixed

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/common/modals/color_palette_modal.vue
app/javascript/common/modals/recurring_calendar_event_modal.vue
app/javascript/components/calendar/calendar.vue

Worked on calendar issue.

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/components/calendar/calendar.vue

Fixed: Calendar map: Event Forms should require Title with both Times selected OR All Day checked.

---

app/javascript/common/navigation_bar.vue

Fixed: The Save Document Key modal should consistently display with the correct saved number of days.

---

app/javascript/common/modals/confirm_save_key_modal.vue

Worked on rather than show a save button, we need to show a delete date with a hover over tool tip that says delete date.

---

app/javascript/components/calendar/calendar.vue

Fixed: calendar tool tip at the bottom of the screen is not visible.

---

app/javascript/components/mindmaps_wrapper.vue
app/javascript/components/password_view.vue

Worked on User should have to submit correct PW to access file Saved Private.

---

app/controllers/mindmaps_controller.rb
app/javascript/components/poll/poll.vue
app/javascript/components/poll/polls/create_poll.vue
app/javascript/components/poll/polls/poll_view.vue
app/javascript/components/poll/polls/poll_view_results/poll_results.vue
app/javascript/components/poll/polls/voting_poll.vue
app/javascript/store/index.js
app/models/mindmap.rb
db/migrate/20221012141024_add_parent_id_to_mindmaps.rb
db/schema.rb

#1018 
#1017 
#1019 
#885 
#942

Poll: Issues Fixed

---

app/controllers/nodes_controller.rb
app/javascript/common/modals/color_palette_modal.vue
app/javascript/components/treemaps/tree_map.vue
app/javascript/mixins/temporary_user.js

Treemap fixed issue on creation & deletion

---

app/models/mindmap.rb
app/models/node.rb

Fixed Duplicate Issues.

---

app/controllers/mindmaps_controller.rb

Fixed clicking 'Duplicate' on Kanban should create duplicate map

---

package.json
yarn.lock

Dependabot alert resolution for trim-newline upgrade.  Tested locally first.

Dependabot alerts

---

app/models/mindmap.rb

Fixed poll unique key issue.

---

app/controllers/mindmaps_controller.rb
app/javascript/components/mindmaps_wrapper.vue

Fixed password modal display issue.

---

app/controllers/concerns/mindmap_concern.rb
app/controllers/mindmaps_controller.rb

Worked on poll unique url and results upon duplication.

---

app/javascript/common/modals/confirm_save_key_modal.vue

Fixed Save Modal button tooltip sync.

---

app/javascript/components/mindmaps/mindmap_new.vue

Fixed Mindmap Nodes Line Drawing issues

---

app/javascript/components/poll/poll.vue
app/javascript/components/poll/polls/create_poll.vue

Fixed poll map Temporary user.

---

app/controllers/concerns/mindmap_concern.rb
app/controllers/mindmaps_controller.rb
app/javascript/common/navigation_bar.vue
app/javascript/components/kanbans/kanban_new.vue
config/routes.rb

Fixed deletion issues upon reload and optimized code

---

app/javascript/components/notepad/notepad.vue

Fixed Notepad Bullets

---

app/controllers/concerns/mindmap_concern.rb
app/controllers/mindmaps_controller.rb
app/controllers/nodes_controller.rb
app/javascript/common/modals/clone_modal.vue
app/javascript/common/navigation_bar.vue
app/javascript/store/index.js
app/models/node.rb
config/routes.rb

Added Duplication in Calendar and Todo.

---

app/javascript/common/modals/clone_modal.vue

Added ToDo: Should include Note on Clone modal

---

app/controllers/concerns/mindmap_concern.rb

Fixed Calendar: Cloned map should have the same numbered dates/times as original.

---

app/controllers/mindmaps_controller.rb
app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/navigation_bar.vue
app/models/mindmap.rb

Issue https://github.com/MicroHealthLLC/mSuite/issues/1074

fix for issue 1074

---

app/javascript/components/poll/polls/create_poll.vue
app/javascript/components/poll/polls/poll_view.vue

Fixes Issue https://github.com/MicroHealthLLC/mSuite/issues/1168

adds dynamic Poll URL for different instances

---

app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/navigation_bar.vue

Fixed conditional issue on is save

---

app/javascript/components/poll/polls/poll_view.vue

Fix for Issue https://github.com/MicroHealthLLC/mSuite/issues/1180

changes button text issue 1180

---

app/controllers/concerns/mindmap_concern.rb
app/controllers/concerns/node_concern.rb
app/controllers/mindmaps_controller.rb
app/controllers/nodes_controller.rb
app/controllers/stages_controller.rb
app/javascript/common/modals/confirm_save_key_modal.vue
app/javascript/common/navigation_bar.vue
app/models/concerns/decryption_concern.rb
app/models/concerns/encryption_concern.rb
app/models/mindmap.rb
app/models/node.rb
app/models/stage.rb
app/services/encryption_service.rb

@bluenevus @juan-rivera-2020 
```
SecureRandom.random_bytes(
ActiveSupport::MessageEncryptor.key_len
)
```
please run this to code in `rails console` to generate the following ENV's  one by one and add them into your .ENV file you will be running this code twice in order to get both strings values
_SECRET_KEY_BASE_
_ENCRYPTION_SERVICE_SALT_

Added Enhancement any map password protected should be 256bit aes encryption.

---

app/models/mindmap.rb
app/models/setting.rb
db/migrate/20221115173404_change_setting_default_value.rb
vendor/assets/javascripts/active_admin.js

Add following env variables in .env file with default value
FAILED_PASSWORD_ATTEMPTS=1
LOCKOUT_PERIOD=1
PERMANENT_LOCK=5
NOTE: we can change the default value as we want.

Fix setting error

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/javascript/components/todo/todo_style.css

Fixes Issue https://github.com/MicroHealthLLC/mSuite/issues/1078

Fixes in sync collab for todo reorder Iss 1078

---

app/javascript/components/poll/polls/voting_poll.vue

Poll Votes Issue Fixed #1338

---

app/javascript/components/poll/polls/create_poll.vue
app/javascript/components/poll/polls/voting_poll.vue

Poll: Removed user requirement issue #1382

---

app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/components/wcag/captions.scss
app/javascript/components/wcag/captions.vue

@bluenevus @LAlexMHllc I've added WCAG text in Mindmap. Kindly test it and let me know if it is the same thing you wish.

Added Captions in Mindmap #709

---

app/channels/web_notifications_channel.rb
app/javascript/components/fileshare/FileShare.vue
app/javascript/components/fileshare/styles.scss
app/javascript/components/home_page.vue
app/javascript/components/mindmaps_wrapper.vue
app/models/mindmap.rb
package.json
yarn.lock

Enhancement: Real Time Peer to Peer File Sharing

---

app/channels/web_notifications_channel.rb
app/controllers/files_controller.rb
app/javascript/common/modals/user_map_modal.vue
app/javascript/common/navigation_bar.vue
app/javascript/components/fileshare/FileShare.vue
app/javascript/components/fileshare/styles.scss
app/models/mindmap.rb
app/models/node.rb
app/services/file_management_service.rb
app/services/file_upload_service.rb
app/workers/delete_file_worker.rb
config/routes.rb
config/schedule.yml
public/uploads/readme.txt

#1436 #1437 #1438 #1439 #1450 #1456 #1457

FileShare: Fixed issues.

---

app/javascript/common/modals/color_palette_modal.vue
app/javascript/components/presentation/Presentation.vue

Presentation: Removed Apply all from texts

---

app/javascript/components/presentation/Presentation.vue
app/models/node.rb

Fixed Presentation map: Export file should not display background icons (imageDisplay div).

---

app/javascript/components/presentation/Presentation.vue
app/javascript/components/presentation/elements/ShapeElement.vue
app/javascript/components/presentation/elements/shapes/EmbedElement.vue

Presentation: Fixed video move and del icon

---

app/channels/web_notifications_channel.rb
app/javascript/components/fileshare/FileShare.vue

Fixed: users can not tell that another user is currently uploading a file

---

app/controllers/mindmaps_controller.rb
app/javascript/components/fileshare/FileShare.vue
app/javascript/components/fileshare/styles.scss

Fileshare: Fixed cancel button and display container

---

app/models/mindmap.rb

Fix duedate sorting for todo and calendar switch

---

app/javascript/components/poll/poll.vue
app/javascript/components/poll/polls/create_poll.vue

Fixes preview button on poll after undo

---

app/controllers/mindmaps_controller.rb
app/controllers/nodes_controller.rb
app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/components/calendar/calendar.vue
app/models/mindmap.rb
app/models/node.rb
db/migrate/20230531204600_add_standalone_to_node.rb
db/schema.rb

Commands to run 
`rake db:migrate`

Added code for standalone events

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/components/calendar/calendar.vue
app/javascript/components/todo/TodoMap.vue
app/models/mindmap.rb
app/models/node.rb

Fixes for Edit Event in Calendar
-  Color Picker
- Title & Date Range
- Standalone Events
#1518

1518 Fixes for Edit Event in Calendar

---

app/javascript/common/navigation_bar.vue
app/javascript/components/calendar/calendar.vue

1515 changes Export icon in Notepad to Word icon

---

app/javascript/common/navigation_bar.vue
app/javascript/components/calendar/calendar.vue
app/javascript/components/mindmaps_wrapper.vue

hides popover on reset click calendar

---

app/javascript/common/modals/add_calendar_event_modal.vue

fixing incorrect white color on sprints

---

app/javascript/components/calendar/calendar.vue

fixes color change on event drag out of sprint

---

app/javascript/components/calendar/calendar.vue

Issues #1529, #1533, #1538, #1541, #1542

fixing issues with event colors

---

app/javascript/components/calendar/calendar.vue

fix for last day of sprint bug

---

app/javascript/components/calendar/calendar.vue

Fix # more modal close on update

---

app/javascript/components/calendar/calendar.vue

fixes modal on event after parent sprint deleted

---

app/javascript/components/calendar/calendar.vue

fixes event on color picker cancel

---

app/javascript/components/calendar/calendar.vue
app/models/node.rb

Fix issue with sprint background

---

app/javascript/components/calendar/calendar.vue

fixes cancel on color picker

---

app/javascript/common/modals/add_calendar_event_modal.vue

fixes incorrect hexcodes

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/components/calendar/calendar.vue

UI improvements to allDay events, and time picker modal

fix all day events and time picker spacing

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/components/calendar/calendar.vue

Fixes #1572. Issue occurred after dragging sprint to change time

fixes time issue with all day events and sprints

---

app/javascript/common/modals/add_calendar_event_modal.vue
app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/javascript/mixins/common.js

added sprints to addTodo

---

app/controllers/nodes_controller.rb
app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/models/node.rb
config/routes.rb

Fixes Todo Drag and Drop

---

app/javascript/components/todo/todo.vue

adds validation for dates on Parent todo

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

Adds more validation on update, Fixes #1587, due date cannot be before start date

fixes update parent todo, #1595 #1587

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue
app/javascript/packs/map_dashboard.js

changing date picker to a more user friendly range

WIP - changes datepickers in todo

---

app/javascript/common/modals/recurring_calendar_event_modal.vue

Removes uneeded clearable icon for reoccurance mod

---

app/javascript/components/calendar/calendar.vue

moves to todays date after delete event

---

app/javascript/components/calendar/calendar.vue

sets current date after reset

---

app/javascript/components/mindmaps/idea_input_field.vue
app/javascript/components/mindmaps/mindmap_new.vue

fixes mindmap issue

---

app/javascript/common/modals/recurring_calendar_event_modal.vue

fixes cancel on recurrence modal

---

app/channels/socket_status_channel.rb
app/controllers/home_controller.rb
app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/serviceworker.js
config/routes.rb

How to test
- open msuite app and open mindmap
- execute `curl -G "http://localhost:3000/socket_status"`
- it will console log in the browser saying socket status success.

Adding websocket status service

---

babel.config.js
config/environments/qa.rb
config/initializers/sidekiq.rb
config/sidekiq.yml
config/webpacker.yml

Added qa environment.
so instead of RAILS_ENV=production or RAILS_ENV=development
write RAILS_ENV=qa

Added qa environment

---

Gemfile
Gemfile.lock

resolves sidekiq dependabot alert https://github.com/MicroHealthLLC/mSuite/security/dependabot/130

Sec alerts 092023

---

app/controllers/mindmaps_controller.rb

Fixed private map issue

---

app/javascript/components/treechart/tree_chart.vue

Fixed Drag and drop for the flow and tree diagrams are single click when it should be click and hold.

---

app/javascript/components/mindmaps/mindmap_new.vue
app/javascript/mixins/temporary_user.js

Removed sendLocals code

---

app/javascript/common/modals/make_private_modal.vue
app/javascript/components/treechart/style/tree_chart.scss
app/javascript/components/treechart/tree_chart.vue

Working on resolving issue 1718 and 1721.

---

app/javascript/components/treechart/tree_chart.vue

Fixed tree map & tree chat collapsed issue

---

app/javascript/components/treemaps/tree_map.vue

Fixed issue Should ONLY drag node when user clicks on icon and holds.

---

app/javascript/components/treechart/tree_chart.vue

Fixed Drag n drop Central node to reposition the entire map.

---

app/javascript/common/modals/recurring_calendar_event_modal.vue

Add Day Functionality In Calender.

---

app/javascript/components/calendar/calendar.vue

Resolve map display issue

---

app/javascript/common/modals/add_calendar_event_modal.vue

Resolve activity card relationship issue

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

Resolve date issue in todo list

---

app/javascript/common/modals/add_calendar_event_modal.vue

Resolve midweek relationship issue

---

app/javascript/components/treemaps/tree_map.scss
app/javascript/components/treemaps/tree_map.vue

Resolve Tree Map Issues.

---

app/javascript/components/todo/TodoMap.vue
app/javascript/components/todo/todo.vue

We've successfully resolved issues related to the Vue Draggable library through custom enhancements. Initially, the Vue Draggable library presented challenges where rows were unintentionally transformed into child rows during dragging. Additionally, there was an issue when dragging a child row outside its parent, creating a new child row under the destination row.
Our custom solution includes the introduction of a 'Make Child' or 'Drag Row' toggle button, offering users more control over the drag-and-drop behavior. When this toggle is on "Drag Row", rows will only be draggable, preventing the creation of child rows or when toggle is "Make Child" rows create the child of that row where we will paste that row. This improvement significantly enhances the usability of our application by …

Add toggle functionality in Todo list

---

app/javascript/common/modals/add_calendar_event_modal.vue

Resolve Related to Dropdown issue

---

package.json

Fixed action cable issue.

---

app/javascript/components/todo/todo.vue

Fixed showing all activities on map.

---

app/javascript/components/todo/todo.vue

Resolve time range event issue
